{% set name = "fastdtw" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "09a24d62a8eb72f87c03692dffae4b8d8499b53f503e9abce5e717c5b705dff9"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
    - pip
    - python
    - Cython
    - setuptools
    - six
    - pytest-runner
  run:
    - numpy
    - python

test:
  imports:
    - fastdtw
  requires:
    - pytest

about:
  home: "https://github.com/slaypni/fastdtw"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Dynamic Time Warping (DTW) algorithm with an O(N) time and memory complexity."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - pgarner
