{% set name = "Unisyn" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: unisyn13.tgz
  md5: b54d18507373959c67ef56125bf698e4

build:
  number: 0
  include_recipe: False

about:
  home: http://www.cstr.ed.ac.uk/projects/unisyn/
  license: Unisyn
  summary: "Unisyn Lexicon Release"
  description: |
    The Unisyn lexicon is a master lexicon transcribed in keysymbols, a kind
    of metaphoneme which allows the encoding of multiple accents of English.

extra:
  recipe-maintainers:
    - pgarner
