{% set name = "librosa" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "f9459dabe09e056e1cba39fe01365e50fb03db2f70f8673cfb2705353b759b81"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - audioread >=2.0.0
    - decorator >=3.0.0
    - joblib >=0.12
    - numba >=0.38.0
    - numpy >=1.15.0
    - pip
    - python
    - resampy >=0.2.0
    - scikit-learn >=0.14.0
    - scipy >=1.0.0
    - six >=1.3
    - soundfile >=0.9.0
  run:
    - audioread >=2.0.0
    - decorator >=3.0.0
    - joblib >=0.12
    - numba >=0.38.0
    - numpy >=1.15.0
    - python
    - resampy >=0.2.0
    - scikit-learn >=0.14.0
    - scipy >=1.0.0
    - six >=1.3
    - soundfile >=0.9.0

test:
  imports:
    - librosa
    - librosa.core
    - librosa.feature
    - librosa.util

about:
  home: "http://github.com/librosa/librosa"
  license: "ISC (ISCL)"
  license_family: "OTHER"
  license_file: ""
  summary: "Python module for audio and music processing"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - pgarner
