{% set name = "sklearn" %}
{% set version = "0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e23001573aa194b834122d2b9562459bf5ae494a2d59ca6b8aa22c85a44c0e31"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - scikit-learn
  run:
    - python
    - scikit-learn

about:
  home: "https://pypi.python.org/pypi/scikit-learn/"
  license: "UNKNOWN"
  license_family: "OTHER"
  license_file: ""
  summary: "A set of python modules for machine learning and data mining"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - pgarner
