{% set name = "resampy" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "62af020d8a6674d8117f62320ce9470437bb1d738a5d06cd55591b69b463929e"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numba >=0.32
    - numpy >=1.10
    - pip
    - python
    - scipy >=0.13
    - six >=1.3
  run:
    - numba >=0.32
    - numpy >=1.10
    - python
    - scipy >=0.13
    - six >=1.3

test:
  imports:
    - resampy

about:
  home: "https://github.com/bmcfee/resampy"
  license: "ISC (ISCL)"
  license_family: "OTHER"
  license_file: ""
  summary: "Efficient signal resampling"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - pgarner
